/*
 * File: app/controller/SteckdosenMaster.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.SteckdosenMaster', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'Steckdose'
        ],
        stores: [
            'Steckdosen'
        ],

        refs: {
            mySteckdosenList: 'steckdosenList'
        },

        control: {
            "list": {
                activate: 'onListActivate',
                itemtap: 'onListItemTap'
            },
            "button[itemId=addSteckdose]": {
                tap: 'onAddSteckdose'
            }
        }
    },

    onListActivate: function(container, newActiveItem, oldActiveItem, eOpts) {
        console.log('Main container is active');
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        alert('Hello')
    },

    onAddSteckdose: function(button, e, eOpts) {
        var employeeForm = Ext.Viewport.down("steckdosenEdit");
        //create the employee edit window if it doesn't exists
        if(!employeeForm){
            employeeForm = Ext.widget("steckdosenEdit");
        } 
        employeeForm.showBy(button);
    }

});