/*
 * File: app/store/Steckdosen.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Dosen', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Dose'
    ],

    config: {
        model: 'MyApp.model.Dose',
        storeId: 'Dosen',
        autoLoad: true,
        data: [
	    	{
	    		id:'1',
	    		idName: 'Dose 1',
		        name: 'Lampe',
		        status_url: 'img/power_off.png'
	    	}, {
	    		id:'2',
	    		idName: 'Dose 2',
	    		name: 'Netzwerk',
	    		status_url: 'img/power_on.png'
	    	}, {
	    		id:'3',
	    		idName: 'Dose 3',
	    		name: 'Netzwerk',
	    		status_url: 'img/power_on.png'
	    	}, {
	    		id:'4',
	    		idName: 'Dose 4',
	    		name: 'Netzwerk',
	    		status_url: 'img/power_on.png'
	    	}
		],
        proxy: {
            type: 'memory'
        }
    }
});