/*
 * File: app/model/Steckdose.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Steckdose', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
		    'name',
		    'internalIp',
		    'externalIp',
		    'typ',
		    'httpPort',
		    'userName',
		    'password',
		    'mac',
		    'version',
        ],
        validations: [
        	{ type: 'presence', field: 'name', message: 'Name'},
        	{ type: 'presence', field: 'typ', message: 'Typ'},
        	{ type: 'presence', field: 'httpPort', message: 'HTTP Port'},
        	{ type: 'presence', field: 'userName', message: 'Benutzername'},
        	{ type: 'presence', field: 'password', message: 'Passwort'},
        ]
    }
});