/*
 * File: app/view/BottomBar.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BottomBar', {
    extend: 'Ext.tab.Panel',

    config: {
        layout: {
            animation: 'fade',
            type: 'card'
        },
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'navigationview',
                        id:'Navigation',
                        items: [
                            {
                                xtype: 'container',
                                title: 'Home',
                                items: [
                                    {
                                        xtype: 'segmentedbutton',
                                        layout: {
                                            pack: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'button',
                                                iconCls: 'add',
                                                text: ''
                                            },
                                            {
                                                xtype: 'button',
                                                iconCls: 'search'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'button',
                                        margin: '10%',
                                        iconCls: 'reply',
                                        text: 'erste Dose',
                                       	handler: function(button){
                                        			button.up('navigationview').push({
                                        				xtype: 'detailpanel',
                                        				title: 'Details'
                                        			});
                                        		 }
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'info'
            }
        ]
    }

});