/*
 * File: app/view/BottomBar.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.BottomBar', {
    extend: 'Ext.tab.Panel',

    requires: [
        'MyApp.view.SteckdosenList'
    ],

    config: {
        layout: {
            animation: 'fade',
            type: 'card'
        },
        tabBar: {
            docked: 'bottom'
        },
        items: [
            {
                xtype: 'container',
                title: 'Home',
                iconCls: 'home',
                layout: {
                    type: 'fit'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'navigationview',
                        id:'navigationview',
                        navigationBar: {
                            docked: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    hidden: false,
                                    itemId: 'addSteckdose',
                                    id: 'addSteckdose',
                                    ui: 'action',
                                    iconCls: 'add'
                                },
                                {
                                    xtype: 'button',
                                    align: 'right',
                                    itemId: 'searchSteckdose',
                                    id:'searchSteckdose',
                                    ui: 'action',
                                    iconCls: 'search'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'container',
                                title: 'Home',
                                id: 'home',
                                layout: {
                                    type: 'fit'
                                },
                                items: [
                                    {
                                        xtype: 'steckdosenList'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Tab 3',
                iconCls: 'info'
            }
        ]
    }

});