/*
 * File: app/view/DetailPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DetailPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.detailpanel',

    config: {
        tabBar: {
            docked: 'top',
            layout: {
                pack: 'center',
                type: 'hbox'
            }
        },
        items: [
            {
                xtype: 'formpanel',
                title: 'Steuerung',
                padding: '10%',
                scrollable: false,
                items: [
                    {
                        xtype: 'togglefield',
                        centered: false,
                        id: 'socketOn',
                        label: 'Dose On',
                        labelWidth: '60%',
                        value: 1,
                        readOnly: true
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'togglefield',
                                docked: 'left',
                                id: 'socket1',
                                width: '80%',
                                label: 'Dose 1',
                                labelWidth: '40%',
                                labelWrap: true
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                icon: 'true',
                                iconAlign: 'center',
                                iconCls: 'settings'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'togglefield',
                                docked: 'left',
                                id: 'socket4',
                                width: '80%',
                                label: 'Dose 1',
                                labelWidth: '40%',
                                labelWrap: true
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                icon: 'true',
                                iconAlign: 'center',
                                iconCls: 'settings'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            pack: 'center',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'togglefield',
                                docked: 'left',
                                id: 'socket5',
                                width: '80%',
                                label: 'Dose 1',
                                labelWidth: '40%',
                                labelWrap: true
                            },
                            {
                                xtype: 'button',
                                docked: 'left',
                                icon: 'true',
                                iconAlign: 'center',
                                iconCls: 'settings'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'bSwitchAll',
                        margin: '3%',
                        text: 'Alle umschalten'
                    },
                    {
                        xtype: 'button',
                        id: 'bSetAllOn',
                        margin: '3%',
                        text: 'Alle einschalten'
                    },
                    {
                        xtype: 'button',
                        id: 'bSetAllOff',
                        margin: '3%',
                        text: 'Alle ausschalten'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Einstellung',
                scrollable: true,
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'verbindungsparameter',
                        title: 'Verbindungsparameter',
                        items: [
                            {
                                xtype: 'urlfield',
                                label: 'IP',
                                labelWidth: '40%',
                                placeHolder: '192.168.1.9'
                            },
                            {
                                xtype: 'textfield',
                                id: 'port',
                                label: 'HTTP Port',
                                labelWidth: '40%',
                                placeHolder: '80'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'benutzerangaben',
                        title: 'Benutzerangaben',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'userName',
                                label: 'Benutzer'
                            },
                            {
                                xtype: 'passwordfield',
                                label: 'Passwort'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'udpParameter',
                        title: 'UDP Parameter',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'udpSendPort',
                                label: 'Senden',
                                labelWidth: '40%',
                                placeHolder: '>1024'
                            },
                            {
                                xtype: 'textfield',
                                id: 'udpReceivePort',
                                label: 'Empfangen',
                                labelWidth: '40%',
                                placeHolder: '>1024'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});