/*
 * File: app/view/DosenPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DosenPanel', {
			extend: 'Ext.form.Panel',
			alias: 'widget.dosenPanel',
			config: {
				items:[
					{
		            	xtype: 'container',
		            	layout: 'vbox',
		            	items:[
		            		{
		            			xtype: 'list',
		            			id:'DosenList',
		            			layout: 'fit',
				                styleHtmlContent: true,
						        emptyText: 'Laden...',
						        loadingText: 'Laden...',
						        height: '20em',
						        variableHeights: true,
						        margin: '20',
						        scrollable: false,
						        itemTpl: [
							    	'<img src="{status_url}" width="40" height="40">{idName}:{name}'								                
						        ],
						        onItemDisclosure: function(record) {
						        	tapOnTimer = true;
						        	console.log("Show Timer");
									console.log(record);
									var timer = 	Ext.create('Ext.form.Panel',{
										title: record.data.name,
										items:[
										{		
											xtype: 'list',
				                			layout: 'fit',
							                styleHtmlContent: true,
									        emptyText: 'Laden...',
									        loadingText: 'Laden...',
									        store: 'Timers',
									        height: '20em',
									        variableHeights: true,
									        margin: '20',
									        scrollable: false,
									        itemTpl: [
										    	'ID:{id};Timer:{name};Time:{startTime}-{endTime};Active:{activated}'								                
									        ]
									 	}]
									});										
									Ext.getCmp('navigationview').push(timer);
								}
		            		}, {
								xtype: 'button',
								margin: '1% 30% 1% 30%',
								padding: '1%',
								text: 'Alle umschalten'					                		
		            		}, {
								xtype: 'button',
								margin: '1% 30% 1% 30%',
								padding: '1%',
								text: 'Alle einschalten'					                		
		            		}, {
								xtype: 'button',
								margin: '1% 30% 1% 30%',
								padding: '1%',
								text: 'Alle ausschalten'					                		
		            		}
		            	]
		            }
				]
			}
});