/*
 * File: app/view/SteckdosenList.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.DosenList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.dosenList',

    config: {
    	onItemDisclosure:true,
        styleHtmlContent: true,
        emptyText: 'Laden...',
        loadingText: 'Laden...',  
		store:'Dosen',     
        variableHeights: true,
        id:'DosenList',
        itemTpl: [
			'<img src="{status_url}" width="40" height="40">{idName}:{name}'
        ]        
    }

});