/*
 * File: app/view/SteckdosenEdit.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MenuTapHold', {
    extend: 'Ext.form.Panel',
    alias: 'widget.menuTapHold',
    id: 'menuTapHold',
    config: {
        fullscreen: false,
			        left: 0,
			        top: 0,
			        tplWriteMode: 'insertAfter',
			        hideOnMaskTap: true,
			        layout: {
			            type: 'fit'
			        },
			        modal: true,
			        defaults: {
			            margin: '0 0 5 0',
			            labelWidth: '30%'
			        },
			        items: [
			            {
			                xtype: 'button',
			                docked: 'left',
			                itemId: 'edit',
			                iconCls: 'action',
			                text: 'bearbeiten',                
			            },
			            {
			                xtype: 'button',
			                docked: 'left',
			                iconCls: 'delete',
			                itemId: 'delete',
			                text: 'l&ouml;schen',
			            }
			        ]
    }

});