/*
 * File: app/view/SteckdosenEdit.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MenuTapHold', {
    extend: 'Ext.form.Panel',
    alias: 'widget.menuTapHold',
    id: 'menuTapHold',

    config: {
        fullscreen: false,
			        left: 0,
			        top: 0,
			        tplWriteMode: 'insertAfter',
			        hideOnMaskTap: true,
			        layout: {
			            type: 'fit'
			        },
			        modal: true,
			        scrollable: false,
			        defaults: {
			            margin: '0 0 5 0',
			            labelWidth: '30%'
			        },
			        items: [
			            {
			                xtype: 'button',
			                docked: 'left',
			                itemId: 'edit',
			                iconCls: 'action',
			                text: 'bearbeiten',
			                handler:function(button){
							    //create the steckdosen edit window if it doesn't exists
							    console.log('Bearbeiten Klick');
							    steckdosenForm = Ext.Viewport.down('steckdosenEdit');
							    if(!steckdosenForm){
							   		steckdosenForm = Ext.widget("steckdosenEdit");
							   	}
			                	steckdosenForm.setRecord(record);
			                	steckdosenForm.showBy(target);
			                	editForm.destroy();
			                }		                
			            },
			            {
			                xtype: 'button',
			                docked: 'left',
			                iconCls: 'delete',
			                itemId: 'delete',
			                text: 'l&ouml;schen',
			                handler:function(button){
			                console.log(record);
			                	var store = Ext.getStore('Steckdosen');
			                	store.remove(store.getById(record.getId()));
			                	Ext.getStore('Steckdosen').sync();
			                	editForm.destroy();
			                }
			            }
			        ]
    }

});