/*
 * File: app/view/SteckdosenList.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SteckdosenList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.steckdosenList',

    config: {
        disabled: false,
        styleHtmlContent: true,
        hideOnMaskTap: true,
        modal: true,
        emptyText: 'Noch keine Steckdose angelegt. Bitte hinzufügen !',
        loadingText: 'Laden...',
        store: 'Steckdosen',
        onItemDisclosure: false,
        variableHeights: true,
        itemTpl: [
            '<div class="steckdosenItem"><div>Name: <b>{name}</b></div><div>Externe IP: <b>{externalIp}</b> interne IP: <b>{internalIp}</b></div><div>Http Port: <b>{httpPort}</b></div></div>'
        ]
    }

});