/*
 * File: app/view/Timer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TimerPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.timer',

    config: {
        centered: false,
        layout: {
            type: 'vbox'
        },
        items: [
        	{
        		xtype: 'textfield',
        		id: 'dosenName',
                docked: 'top',
                label: 'Name',
        	},
        	{
        		xtype:'list',
        		flex: 1,
        		variableHeights: true,
        		styleHtmlContent: true,
        		itemTpl: [
        			'<div class=timer><div class="time">{startTime}</div><div class="time">{endTime}</div><div class="timerName">{name}</div><br/>'+
        			'<div class="{MO}">Mo</div>'+
        			'<div class="{DI}">Di</div>'+
        			'<div class="{MI}">Mi</div>'+
        			'<div class="{DO}">Do</div>'+
        			'<div class="{FR}">Fr</div>'+
        			'<div class="{SA}">Sa</div>'+
        			'<div class="{SO}">So</div>'+ '<input class="timerCheckBox" type="checkbox" {checked}/></div>'
        		]
        	},
        	{
				xtype: 'button',
				itemId: 'saveTimer',
				margin: '1% 25% 5% 25%',
				padding: '1%',
				text: 'speichern'      	
        	}
        ]
    }

});