/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'Steckdose',
        'Dose',
        'Timer'
    ],
    stores: [
        'Steckdosen',
        'Dosen',
        'Timers'
    ],
    views: [
        'DetailPanel',
        'BottomBar',
        'Timer',
        'SteckdosenList',
        'SteckdosenEdit'
    ],
    controllers: [
        'SteckdosenMaster'
    ],
    name: 'MyApp',

    launch: function() {

        Ext.create('MyApp.view.BottomBar', {fullscreen: true});
    }

});
